services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  auth:
    build:
      context: .
      dockerfile: ./app/auth/Dockerfile
    container_name: auth-service
    env_file:
      - ./env/.env.${ENVIRONMENT:-stg}
    ports:
      - "9001:9001"
    depends_on:
      - redis

  chat:
    build:
      context: .
      dockerfile: ./app/chat/Dockerfile
    container_name: chat-service
    env_file:
      - ./env/.env.${ENVIRONMENT:-stg}
    ports:
      - "9002:9002"
    depends_on:
      - redis
